- name: Install Atuin
  tags: [ atuin ]
  shell: bash <(curl --proto '=https' --tlsv1.2 -sSf https://setup.atuin.sh)
  args:
    creates: "{{ home }}/.atuin/bin/atuin"
    executable: /bin/bash
  register: atuin_install

- name: Remove line Atuin adds to .bashrc
  tags: [ atuin ]
  lineinfile:
    path: "{{ home }}/.bashrc"
    line: 'eval "$(atuin init bash)"'
    state: absent

- name: Disable up arrow for Atuin
  tags: [ atuin ]
  lineinfile:
    path: "{{ home }}/.bashrc"
    line: 'eval "$(atuin init bash --disable-up-arrow)"'
    state: present

- name: Update Atuin
  tags: [ atuin ]
  shell: "{{ home }}/.atuin/bin/atuin-update"
  register: atuin_update
  changed_when:
    - '"Already up to date" not in atuin_update.stderr'

- name: Import existing shell history
  tags: [ atuin ]
  shell: "{{ home }}/.atuin/bin/atuin import auto"
  when: atuin_install.changed

- name: Generate completions for atuin
  tags: [ atuin ]
  shell: "{{ home }}/.atuin/bin/atuin gen-completions --shell bash --out-dir $HOME"
  when: atuin_install.changed or atuin_update.changed
